# Generated by Django 4.2.5 on 2023-09-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lombard_app', '0005_alter_loan_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_date', models.DateField(auto_now_add=True)),
                ('new_due_date', models.DateField()),
                ('extension_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='lombard_app.loan')),
            ],
        ),
    ]
